before_script: npm install -g harp
script: bash ./deploy.sh
language: node_js
node_js:
  - 5.7.1
env:
  global:
    - GH_REF: github.com/bionode/bionode.github.io.git
    - secure: IfUmyNuaYjeRtiXneopAmClPSziRqqcqiunFeG7oXenGR5s9AkgSNtAyCMPUGYcDtYKAtwv1bxWhKgXaOcMhd16pjVBqgi6rb+uAR9+VWC7imWd9cnXz9RvLjTSmE3Y8cK93/wpv5sCpQZvRczSddGvb8/PPbw4iePT42xwwFA4=
branches:
  only:
    - dev
