before_script: npm install -g harp
script: bash ./deploy.sh
language: node_js
node_js:
  - 5.7.1
before_install:
  - cd $HOME
  - wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-1.5.tar.gz
  - tar -zxvf jq-1.5.tar.gz
  - cd jq-1.5
  - ./configure --disable-maintainer-mode
  - make -j8
  - sudo make install
  - alias jq=$HOME/jq
  - cd $TRAVIS_BUILD_DIR
env:
  global:
    - GH_REF: github.com/bionode/bionode.github.io.git
    - secure: IfUmyNuaYjeRtiXneopAmClPSziRqqcqiunFeG7oXenGR5s9AkgSNtAyCMPUGYcDtYKAtwv1bxWhKgXaOcMhd16pjVBqgi6rb+uAR9+VWC7imWd9cnXz9RvLjTSmE3Y8cK93/wpv5sCpQZvRczSddGvb8/PPbw4iePT42xwwFA4=
branches:
  only:
    - dev
